### ISSUE TITLE
Robot spins at the end

### ISSUE THREAD

**Issue by kevin-robb** [SoonerRobotics/scr_simulator#1]
When the generated trajectory has been followed and it reaches the last waypoint, my code starts sending drive commands of heading=0 and speed=0, but when this happens the robot just spins counterclockwise in place. It also spins as it moves to the finish line after the last turn_end waypoint. It doesn't spin constantly, but rather seems to spin fully around, pause at 0 degrees, and spin again. This does not stop until I close the simulator.

**Comment by kevin-robb** [comment]
FIXED on my end, because it turns out I can't send you a heading of 0 or it screws up, pls fix on your end. Making it check on my end and sending 360 instead of 0 works fine.

**Comment by noahzemlin** [comment]
Not going to fix. I intend to remove accepting DriveCommand (including the code responsible for this bug) in favor of only accepting raw motor command (-1.0 to 1.0 on each wheel)
