### ISSUE TITLE
Physics Question

### ISSUE THREAD

**Issue by jkleiber** [SoonerRobotics/scr_simulator#2]
https://github.com/SoonerRobotics/scr_simulator/blob/d552972f51596710a656a428badb38f965af7eaa/Assets/Scripts/SimpleCarController.cs#L46
https://github.com/SoonerRobotics/scr_simulator/blob/d552972f51596710a656a428badb38f965af7eaa/Assets/Scripts/SimpleCarController.cs#L51
https://github.com/SoonerRobotics/scr_simulator/blob/d552972f51596710a656a428badb38f965af7eaa/Assets/Scripts/SimpleCarController.cs#L52

Where did these equations come from? The equations I have for differential drive velocity are listed here: https://github.com/SoonerRobotics/igvc_software_2020/blob/master/docs/IGVC_Kalman_Filter_Derivation.pdf
(specifically page 2, differential drive approximation)

My main concern is the lack of inclusion of the wheel radius in the calculation of psi_dot, as well as the different looking equation for the x and y velocities.

My original source: http://planning.cs.uiuc.edu/node659.html

A new source I found with similar equations, but with the addition of a transformation to find the x,y coordinates of the geometric center in addition to the turn center (the EKF only cares about the center of turn so I don't include this): https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=3&ved=2ahUKEwid2qX279fnAhVBXawKHRfsD78QFjACegQIBBAB&url=https%3A%2F%2Fwww.mdpi.com%2F2218-6581%2F6%2F3%2F17%2Fpdf&usg=AOvVaw1eN1d047xcYka3NTjWhd-I

**Comment by noahzemlin** [comment]
The equations used came from Stephanie who helped me solve for them. I tried using the equations you sent but had some issues having them work correctly. I do want to switch to the equations you linked eventually.
